language: swift
osx_image: xcode10.1
xcode_workspace: Example/PerspectiveTransform.xcworkspace
xcode_scheme: Example
xcode_sdk: iphonesimulator12.1
git:
  depth: false
cache:
  bundler: true
  cocoapods: true
bundler_args: --no-deployment
podfile: Example/Podfile
stages:
  - test
  - deploy
matrix:
  include:
    name: Mac OS
    xcode_scheme: OpenCV Tests
    env: XCODE_DESNITATION='platform=macos' CACHE_NAME=macOS
    before_script: ./Example/OpenCV-OSX-Tests/install-opencv.sh
    cache:
      bundler: true
      cocoapods: true
      directories: # Cache opencv with dependecies
        - /usr/local/opt/
        - /usr/local/Cellar/opencv@2
        - /usr/local/Cellar/ffmpeg
        - /usr/local/Cellar/ilmbase
        - /usr/local/Cellar/snappy
        - /usr/local/Cellar/opencore-amr
        - /usr/local/Cellar/speex
        - /usr/local/Cellar/theora
        - /usr/local/Cellar/rtmpdump
        - /usr/local/Cellar/libogg
        - /usr/local/Cellar/libvorbis
        - /usr/local/Cellar/opus
        - /usr/local/Cellar/jpeg
        - /usr/local/Cellar/lame
        - /usr/local/Cellar/libpng
        - /usr/local/Cellar/libtiff
        - /usr/local/Cellar/openexr
        - /usr/local/Cellar/openssl
        - /usr/local/Cellar/x264
        - /usr/local/Cellar/x265
before_install:
  - bundle -v || gem install bundler
  - ls -la Example/Pods/Manifest.lock && echo Skipping cocoapods repo update || git -C ~/.cocoapods/repos/master/ pull --quiet
script:
  - set -o pipefail && xcodebuild test -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$XCODE_DESNITATION" | bundle exec xcpretty -f `bundle exec xcpretty-travis-formatter`
branches:
  except:
  - circleci
